//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryDataApp.ResourceProviderServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResourceProviderServiceReference.IResourceProviderService")]
    public interface IResourceProviderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceProviderService/QueryAvailableResource", ReplyAction="http://tempuri.org/IResourceProviderService/QueryAvailableResourceResponse")]
        string[] QueryAvailableResource();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResourceProviderService/QueryAvailableResource", ReplyAction="http://tempuri.org/IResourceProviderService/QueryAvailableResourceResponse")]
        System.Threading.Tasks.Task<string[]> QueryAvailableResourceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResourceProviderServiceChannel : QueryDataApp.ResourceProviderServiceReference.IResourceProviderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResourceProviderServiceClient : System.ServiceModel.ClientBase<QueryDataApp.ResourceProviderServiceReference.IResourceProviderService>, QueryDataApp.ResourceProviderServiceReference.IResourceProviderService {
        
        public ResourceProviderServiceClient() {
        }
        
        public ResourceProviderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResourceProviderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceProviderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceProviderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] QueryAvailableResource() {
            return base.Channel.QueryAvailableResource();
        }
        
        public System.Threading.Tasks.Task<string[]> QueryAvailableResourceAsync() {
            return base.Channel.QueryAvailableResourceAsync();
        }
    }
}
